//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateDatabaseSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateDatabaseSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizMaker.Resources.CreateDatabaseSql", typeof(CreateDatabaseSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;Answer&quot; (
        ///	&quot;Answer_ID&quot;	INTEGER,
        ///	&quot;Question_ID&quot;	INTEGER NOT NULL,
        ///	&quot;Answer_Text&quot;	TEXT NOT NULL,
        ///	&quot;Answer_Field&quot;	INTEGER NOT NULL,
        ///	&quot;Answer_IsCorrect&quot;	INTEGER NOT NULL DEFAULT 0 CHECK(&quot;Answer_IsCorrect&quot; IN (0, 1)),
        ///	PRIMARY KEY(&quot;Answer_ID&quot;),
        ///	FOREIGN KEY(&quot;Question_ID&quot;) REFERENCES &quot;Question&quot;(&quot;Question_ID&quot;)
        ///).
        /// </summary>
        internal static string CreateAnswersTable {
            get {
                return ResourceManager.GetString("CreateAnswersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;Question&quot; (
        ///	&quot;Question_ID&quot;	INTEGER,
        ///	&quot;Quiz_ID&quot;	INTEGER NOT NULL,
        ///	&quot;Question_Name&quot;	TEXT NOT NULL,
        ///	&quot;Question_Order&quot;	INTEGER NOT NULL,
        ///	PRIMARY KEY(&quot;Question_ID&quot;),
        ///	FOREIGN KEY(&quot;Quiz_ID&quot;) REFERENCES &quot;Quiz&quot;(&quot;Quiz_ID&quot;)
        ///).
        /// </summary>
        internal static string CreateQuestionsTable {
            get {
                return ResourceManager.GetString("CreateQuestionsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;Quiz&quot; (
        ///	&quot;Quiz_ID&quot;	INTEGER,
        ///	&quot;Quiz_Name&quot;	TEXT NOT NULL,
        ///	PRIMARY KEY(&quot;Quiz_ID&quot;)
        ///).
        /// </summary>
        internal static string CreateQuizTable {
            get {
                return ResourceManager.GetString("CreateQuizTable", resourceCulture);
            }
        }
    }
}
